# Generated by Django 6.0.3 on 2026-05-28 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('amount', models.FloatField(default=10000.0)),
            ],
        ),
        migrations.CreateModel(
            name='Cpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(unique=True)),
                ('cpi_value', models.FloatField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('tipsId', models.AutoField(primary_key=True, serialize=False)),
                ('cusip', models.CharField(max_length=12, unique=True)),
                ('dated_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('coupon_rate', models.FloatField()),
                ('ref_cpi', models.FloatField()),
                ('index_ratio', models.FloatField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('ladderId', models.AutoField(primary_key=True, serialize=False)),
                ('tax_rate', models.FloatField(default=15.0)),
                ('start_year', models.IntegerField(default=2024)),
                ('end_year', models.IntegerField(default=2030)),
                ('future_inflation', models.FloatField(default=0.0)),
                ('use_pretax', models.BooleanField(default=False)),
                ('inflate_base_cash_flow', models.BooleanField(default=False)),
                ('date_of_base_cash_flow', models.DateField(default='2024-01-01')),
                ('cash_flows', models.ManyToManyField(blank=True, related_name='cash_flows', to='core.cashflow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owned_tips', models.ManyToManyField(blank=True, to='core.tips')),
            ],
        ),
    ]
