# Generated by Django 6.0.3 on 2026-05-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spec',
            old_name='cash_flows',
            new_name='addl_cash_flows',
        ),
        migrations.AddField(
            model_name='spec',
            name='base_cash_flow',
            field=models.FloatField(default=10000.0),
        ),
    ]
