# Generated by Django 6.0.3 on 2026-06-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='additional_flows',
            field=models.ManyToManyField(related_name='acash_flows', to='core.cashflow'),
        ),
    ]
