# Generated by Django 6.0.3 on 2026-05-26 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladder',
            name='base_cash_flow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_cash_flow', to='core.cashflow'),
        ),
    ]
