# Generated by Django 6.0.3 on 2026-05-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ladder_base_cash_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
