# Generated by Django 6.0.3 on 2026-06-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_specs_additional_flows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='additional_flows',
            field=models.ManyToManyField(related_name='in_specs', to='core.cashflow'),
        ),
    ]
