# Generated by Django 6.0.3 on 2026-06-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_specs_additional_flows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owned_tips',
            options={'ordering': ['tips']},
        ),
        migrations.RenameField(
            model_name='owned_tips',
            old_name='owned_tips_user',
            new_name='user',
        ),
    ]
